name: release

on:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

permissions:
  contents: write
  issues: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '3.1.x'

      - name: prepare csharp-dotnet-sdk
        run: |
          dotnet build --configuration Release

          dotnet test --configuration Release --no-restore

          dotnet pack --configuration Release --no-build --no-restore --output .

      - uses: cycjimmy/semantic-release-action@v4.0.0
        with:
          semantic_version: 18
          extra_plugins: |
            @semantic-release/changelog@6.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish package distributions to NuGet
        run: |
          dotnet nuget push \
            "$(ls -a AffixApi.Api.*.nupkg)" \
            --source https://api.nuget.org/v3/index.json \
            -k ${{ secrets.NUGET_API_KEY }}
