name: release

on:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

permissions:
  contents: write
  issues: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '3.1.x'

      - name: prepare csharp-dotnet-sdk
        run: |
          echo 'building'

          dotnet build --configuration Release

          echo 'packing'

          dotnet pack \
            --no-restore \
            --no-build \
            --configuration Release \
            --output .

      - uses: cycjimmy/semantic-release-action@v4.0.0
        with:
          semantic_version: 18
          extra_plugins: |
            @semantic-release/changelog@6.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish package distributions to NuGet
        run: |
          dotnet nuget push \
            AffixApi.${{ github.ref_name }}.nopkg \
            -s https://nuget.pkg.github.com/affixapi/csharp-dotnet-sdk/index.json \
            -k ${{ secrets.NUGET_AUTH_TOKEN }}
